import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
df = pd.read_csv('https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DV0101EN-SkillsNetwork/Data%20Files/airline_data.csv')
print(df.head())
data = df.sample(n=500,random_state=42)
print(data.shape)
fig = go.Figure(data=go.Scatter(x=data['Distance'],y=data['DepTime'],mode='markers',marker=dict(color='red')))
fig.update_layout(title='Distance vs Departure Time',xaxis_title='Distance',yaxis_title='Departure Time')
fig.show()
line = data.groupby('Month')['ArrDelay'].mean().reset_index()
print(line)
fig =go.Figure(data=go.Scatter(x=line['Month'],y=line['ArrDelay'],mode='lines',marker=dict(color='red')))
fig.update_layout(title='Month vs Arrival Delay',xaxis_title='Month',yaxis_title='Arrival Delay')
#fig.show()
bar = data.groupby(['DestState'])['Flights'].sum().reset_index()
print(bar)
fix = px.bar(bar,x='DestState',y='Flights',title='Total Number of Flights to Destination State')
#fix.show()
bub = data.groupby('Reporting_Airline')['Flights'].sum().reset_index()
print(bub)
fig = px.scatter(bub,x='Reporting_Airline',y='Flights',size='Flights',hover_name='Reporting_Airline',title='Reporting_Airline vs Flights',size_max=60)
#fig.show()
data['ArrDelay']=data['ArrDelay'].fillna(0)
fig = px.histogram(data,x='ArrDelay')
#fig.show()
fig = px.pie(data,values='Month',names='DistanceGroup',title='Distance group proportion by month')
fig.show()
fig=px.sunburst(data,path=['Month','DestStateName'],values='Flights')
fig.show()
