import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df= pd.read_excel('Canada.xlsx',sheet_name='Canada by Citizenship',skiprows=range(20),skipfooter=2)
print(df.head())
print(df.columns)
df.drop(['Type','Coverage','AREA','REG','DEV'],axis=1,inplace=True)
df.drop(['Unnamed: 43','Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46', 'Unnamed: 47','Unnamed: 48', 'Unnamed: 49', 'Unnamed: 50'],axis=1,inplace=True)
df.rename(columns={'OdName':'Country','AreaName':'Continent','RegName':'Region'},inplace=True)
df['Total']=df.sum(axis=1)
print(df.head())
print(df.Country[0:11])
print(df[['Country',1980]][0:11])
df.set_index('Country',inplace=True)
print(df.head())
df.columns = list(map(str,df.columns))
years = list(map(str,range(1980,2014)))
print(df.loc['India',years].to_frame()[0:11])
haiti = df.loc['Haiti',years]
haiti.index = haiti.index.map(int)
haiti.plot()
plt.title('Graph')
plt.xlabel('Years')
plt.ylabel('Number of Immigrants')
plt.show()
plt.close()
dfci = df.loc[['India','China'],years]
dfci = dfci.transpose()
dfci.plot()
plt.title('Graph')
plt.xlabel('Years')
plt.ylabel('Number of Immigrants')
plt.show()
plt.close()
df.sort_values(by='Total',ascending=False,axis=0,inplace=True)
df5 = df.head(5)
df5 = df5[years].transpose()
print(df5)
df5.plot(kind='line')
plt.title('Graph')
plt.xlabel('Years')
plt.ylabel('Number of Immigrants')
plt.show()
plt.close()