import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
df = pd.read_excel('Canada.xlsx',sheet_name='Canada by Citizenship',skiprows=range(20),skipfooter=2)
df.drop(['Type','AREA','REG','DEV','Coverage','Unnamed: 43','Unnamed: 44','Unnamed: 45','Unnamed: 46','Unnamed: 47','Unnamed: 48','Unnamed: 49','Unnamed: 50'],axis=1,inplace=True)
df.rename(columns={'OdName':'Country','RegName':'Region','AreaName':'Continent'},inplace=True)
print(df.head())
df['Total'] = df.sum(axis=1)
df.set_index('Country',inplace=True)
print(df.head())
df.columns = list(map(str,df.columns))
years = list(map(str,range(1980,2014)))
df.sort_values(by='Total',ascending=False,axis=0,inplace=True)
df5 = df.head()
print(df5)
df5 = df5[years].transpose()
df5.index = df5.index.map(int)
#df5.plot(kind='area',alpha=0.35,figsize=(20,10))
plt.title('Number of Migrants From India(1980 to 2013)')
plt.xlabel('Years')
plt.ylabel('Number of Migrants')
plt.close()
dfC = df.loc['China',years]
#dfC.plot(kind='bar')
plt.title('Number of Migrants From China(1980 to 2013)')
plt.xlabel('Years')
plt.ylabel('Number of Migrants')
plt.close()
dfcon = df.groupby('Continent',axis=0).sum()
print(dfcon)
#colorlist = ['gold', 'yellowgreen', 'lightcoral', 'lightskyblue', 'lightgreen', 'pink']
explodelist = [0.1,0.1,0.1,0.1,0.1,0.1]
#dfcon['Total'].plot(kind='pie',autopct="%1.1f%%",startangle=90,shadow=True,explode=explodelist)
#plt.axis('equal')
dfj = df.loc['Japan',years]
dfci = df.loc[['India','China'],years].transpose()
dftot = pd.DataFrame(df[years].sum(axis=0))
dftot.index = dftot.index.map(int)
dftot.reset_index(inplace=True)
dftot.columns = ['Year','Total']
print(dftot.head())
x = dftot['Year']
y = dftot['Total']
fit=np.polyfit(x,y,1)
print(fit)
dft = df[years].transpose()
dft.index = dft.index.map(int)
dft.index.name = 'Years'
dft.reset_index(inplace=True)
print(dft.head())
print(df.loc[['Pakistan','India'],years].head())
npak = (dft['Pakistan']-dft['Pakistan'].min())/(dft['Pakistan'].max()-dft['Pakistan'].min())
nindia = (dft['India']-dft['India'].min())/(dft['India'].max()-dft['India'].min())
norm_china = (dft['China']-dft['China'].min())/(dft['China'].max()-dft['China'].min())
print(npak[0:11],nindia[0:11])
dax = dft.plot(kind='scatter',x='Years',y='Pakistan',figsize=(20,6),alpha=0.5,color='blue',s=npak*2000+10)
fig = plt.figure()
ax1 = fig.add_subplot(3,2,1)
ax2 = fig.add_subplot(3,2,2)
ax3 = fig.add_subplot(3,2,3)
ax4 = fig.add_subplot(3,2,4)
ax5 = fig.add_subplot(3,2,5)
ax6 = fig.add_subplot(3,2,6)
df5.plot(kind='area',alpha=0.35,figsize=(20,10),ax=ax1)
ax1.set_title('Number of Migrants From India(1980 to 2013)')
ax1.set_xlabel('Years')
ax1.set_ylabel('Number of Migrants')
dfcon['Total'].plot(kind='pie',figsize=(20,10),autopct="%1.1f%%",startangle=90,shadow=True,explode=explodelist,ax=ax2)
ax2.axis('equal')
ax2.legend(labels=dfcon.index,loc='center left')
dftot.plot(kind='scatter',figsize=(20,10),x='Year',y='Total',ax=ax3)
ax3.set_xlabel('Years')
ax3.set_ylabel('Number of Migrants')
ax3.set_title('Number of Migrants From India(1980 to 2013)',loc='left')
dfci .plot(kind='line',figsize=(20,10),ax=ax4)
ax4.set_title('Number of Migrants From India(1980 to 2013)')
ax4.set_xlabel('Years')
ax4.set_ylabel('Number of Migrants')
ax0 = dft.plot(kind='scatter',x='Years',y='India',alpha=0.5,color='green',s=nindia*2000+10,ax=ax5)
ax5.set_title('Bubble Plot')
ax5.set_ylabel('Number of Immigrants')
ax5.legend(['Brazil', 'India'], loc='upper left', fontsize='x-large')
dfax = dft.plot(kind='scatter',x='Years',y='China',alpha=0.5,color="green",s=norm_china * 2000 + 10,ax = ax6)
dft.plot(kind='scatter',x='Years',y='India',alpha=0.5,color="blue",s=nindia * 2000 + 10,ax = dfax)
ax6.set_ylabel('Number of Immigrants')
ax6.set_title('Immigration from China and India from 1980 - 2013')
ax6.legend(['China', 'India'], loc='upper left', fontsize='x-large')
plt.show()
plt.close()

